
import asyncio
import sys
import os
from datetime import datetime, date, timedelta
from uuid import uuid4

# ENV VARS will be provided by container
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import select
from app.core.database import AsyncSessionLocal
from app.models.startup import Startup, Sprint
from app.models.growth import Lead, LeadStatus, LeadSource

# 1. Technical Creatives for Symbiotask
SYRBIOTASK_LEADS = [
    {
        "company": "Cinematic AI",
        "contact": "Bilawal Sidhu",
        "email": "bilawal@creator.com",
        "title": "AI Filmmaker",
        "industry": "VFX/AI",
        "linkedin": "https://linkedin.com/in/bilawalsidhu",
        "tags": ["Technical Creative", "Sora User", "High Priority"]
    },
    {
        "company": "Future XR",
        "contact": "Don Allen Stevenson",
        "email": "don@creator.com",
        "title": "XR Specialist",
        "industry": "XR/Spatial",
        "linkedin": "https://linkedin.com/in/donalleniii",
        "tags": ["Technical Creative", "Nano Banana Target"]
    },
    {
        "company": "Runway Power Users",
        "contact": "Karen X. Cheng",
        "email": "karen@creative.com",
        "title": "Director",
        "industry": "Advertising",
        "tags": ["Viral Creator", "Symbiotask Beta"]
    }
]

# 2. Ambassador Prospects (Stripe Connect) for MomentAIc
AMBASSADORS = [
    {
        "company": "The AI Solopreneur",
        "contact": "Ole Lehmann",
        "email": "ole@newsletter.com",
        "title": "Newsletter Creator",
        "industry": "Media",
        "tags": ["Ambassador Prospect", "Stripe Connect", "High Volume"]
    },
    {
        "company": "Superhuman AI",
        "contact": "Zain Kahn",
        "email": "zain@superhuman.ai",
        "title": "Founder",
        "industry": "Media",
        "tags": ["Ambassador Prospect", "Stripe Connect"]
    }
]

async def seed_growth():
    print("🌱 SEEDING GROWTH DATA (Leads & Sprints)...")
    async with AsyncSessionLocal() as db:
        # Get Startups
        stmt = select(Startup)
        result = await db.execute(stmt)
        startups = {s.name: s for s in result.scalars().all()}
        
        symbiotask = startups.get("Symbiotask")
        momentaic = startups.get("MomentAIc")
        
        if not symbiotask or not momentaic:
            print("❌ Startups not found. Run seed_empire.py first.")
            return

        # 1. Seed Symbiotask Leads (Technical Creatives)
        print("   ► Seeding Symbiotask Leads...")
        count = 0
        for l in SYRBIOTASK_LEADS:
             # Check for dupe by email
            exists = await db.execute(select(Lead).where(Lead.contact_email == l["email"]))
            if not exists.scalar_one_or_none():
                lead = Lead(
                    startup_id=symbiotask.id,
                    company_name=l["company"],
                    contact_name=l["contact"],
                    contact_email=l["email"],
                    contact_title=l["title"],
                    company_industry=l["industry"],
                    contact_linkedin=l.get("linkedin"),
                    source=LeadSource.MANUAL,
                    status=LeadStatus.NEW,
                    tags=l["tags"],
                    notes="Generated by Zero-Budget Growth Strategy Plan. Target for 'Movie Blueprint' outreach."
                )
                db.add(lead)
                count += 1
        print(f"     ✅ Added {count} Technical Creatives.")

        # 2. Seed MomentAIc Ambassadors
        print("   ► Seeding Ambassadors...")
        count = 0
        for a in AMBASSADORS:
            exists = await db.execute(select(Lead).where(Lead.contact_email == a["email"]))
            if not exists.scalar_one_or_none():
                lead = Lead(
                    startup_id=momentaic.id, # Ambassadors belong to the platform
                    company_name=a["company"],
                    contact_name=a["contact"],
                    contact_email=a["email"],
                    contact_title=a["title"],
                    company_industry=a["industry"],
                    source=LeadSource.REFERRAL,
                    status=LeadStatus.NEW,
                    tags=a["tags"],
                    notes="Stripe Connect onboarding target."
                )
                db.add(lead)
                count += 1
        print(f"     ✅ Added {count} Ambassadors.")

        # 3. Product Hunt Launch Sprints
        print("   ► Creating 'Product Hunt Launch' Sprints...")
        for name, startup in startups.items():
            if name in ["Symbiotask", "Bondquests", "AgentForge AI", "MomentAIc"]:
                sprint = Sprint(
                    startup_id=startup.id,
                    goal="Product Hunt Launch 🚀",
                    key_results=[
                        "Get 500 upvotes",
                        "Reach #1 Product of the Day",
                        "Respond to all comments strictly within 5 mins"
                    ],
                    start_date=date.today(),
                    end_date=date.today() + timedelta(days=14),
                    status="active",
                    progress_percentage=10
                )
                db.add(sprint)
        print("     ✅ Sprints created for all 4 Startups.")

        await db.commit()
        print("🚀 GROWTH DATA SEEDED SUCCESSFULLY.")

if __name__ == "__main__":
    asyncio.run(seed_growth())
