"""add_acquisition_channels

Revision ID: 9ef90fa44811
Revises: 002_integrations_triggers
Create Date: 2025-12-26 16:03:48.160845

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ef90fa44811'
down_revision: Union[str, None] = '002_integrations_triggers'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'acquisition_channels',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('startup_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('channel_type', sa.String(length=50), nullable=False),
        sa.Column('platform', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('monthly_budget', sa.Float(), nullable=False),
        sa.Column('total_spend', sa.Float(), nullable=False),
        sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['startup_id'],
            ['startups.id'],
            name=op.f('fk_acquisition_channels_startup_id_startups'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_acquisition_channels')),
    )
    op.create_index(
        'ix_channel_startup_type',
        'acquisition_channels',
        ['startup_id', 'channel_type'],
        unique=False,
    )
    op.create_table(
        'channel_metrics',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('channel_id', sa.UUID(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('impressions', sa.Integer(), nullable=False),
        sa.Column('clicks', sa.Integer(), nullable=False),
        sa.Column('leads_count', sa.Integer(), nullable=False),
        sa.Column('conversions_count', sa.Integer(), nullable=False),
        sa.Column('spend', sa.Float(), nullable=False),
        sa.Column('revenue', sa.Float(), nullable=False),
        sa.Column('cac', sa.Float(), nullable=False),
        sa.Column('roas', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['channel_id'],
            ['acquisition_channels.id'],
            name=op.f('fk_channel_metrics_channel_id_acquisition_channels'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_metrics')),
    )
    op.create_index(
        'ix_metric_channel_date', 'channel_metrics', ['channel_id', 'date'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metric_channel_date', table_name='channel_metrics')
    op.drop_table('channel_metrics')
    op.drop_index('ix_channel_startup_type', table_name='acquisition_channels')
    op.drop_table('acquisition_channels')
    # ### end Alembic commands ###
