"""add_agent_memory_outcome_fingerprint_tables

Revision ID: bd78173abb1b
Revises: 20260115_184500_ee1e12345678
Create Date: 2026-02-11 17:28:13.297128

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd78173abb1b'
down_revision: Union[str, None] = '20260115_184500_ee1e12345678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'agent_memory_store',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('startup_id', sa.UUID(), nullable=False),
        sa.Column('agent_name', sa.String(length=100), nullable=False),
        sa.Column(
            'memory_type',
            sa.Enum('fact', 'preference', 'learning', 'strategy', 'warning', name='memorytype'),
            nullable=False,
        ),
        sa.Column('key', sa.String(length=255), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('importance', sa.Integer(), nullable=False),
        sa.Column('access_count', sa.Integer(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['startup_id'],
            ['startups.id'],
            name=op.f('fk_agent_memory_store_startup_id_startups'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_memory_store')),
    )
    op.create_index('ix_memstore_key', 'agent_memory_store', ['startup_id', 'key'], unique=False)
    op.create_index(
        'ix_memstore_startup_agent',
        'agent_memory_store',
        ['startup_id', 'agent_name'],
        unique=False,
    )
    op.create_index('ix_memstore_type', 'agent_memory_store', ['memory_type'], unique=False)
    op.create_table(
        'agent_outcomes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('startup_id', sa.UUID(), nullable=False),
        sa.Column('agent_name', sa.String(length=100), nullable=False),
        sa.Column('action_type', sa.String(length=100), nullable=False),
        sa.Column('input_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            'outcome_status',
            sa.Enum('pending', 'successful', 'failed', 'neutral', name='outcomestatus'),
            nullable=False,
        ),
        sa.Column('outcome_metric', sa.String(length=100), nullable=True),
        sa.Column('outcome_value', sa.Float(), nullable=True),
        sa.Column('outcome_notes', sa.Text(), nullable=True),
        sa.Column('tokens_used', sa.Integer(), nullable=False),
        sa.Column('execution_time_ms', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('resolved_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['startup_id'],
            ['startups.id'],
            name=op.f('fk_agent_outcomes_startup_id_startups'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_outcomes')),
    )
    op.create_index('ix_outcomes_created', 'agent_outcomes', ['created_at'], unique=False)
    op.create_index(
        'ix_outcomes_startup_agent', 'agent_outcomes', ['startup_id', 'agent_name'], unique=False
    )
    op.create_index('ix_outcomes_status', 'agent_outcomes', ['outcome_status'], unique=False)
    op.create_table(
        'lead_fingerprints',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('startup_id', sa.UUID(), nullable=False),
        sa.Column('fingerprint_hash', sa.String(length=64), nullable=False),
        sa.Column('source_agent', sa.String(length=100), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['startup_id'],
            ['startups.id'],
            name=op.f('fk_lead_fingerprints_startup_id_startups'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_fingerprints')),
        sa.UniqueConstraint('fingerprint_hash', name=op.f('uq_lead_fingerprints_fingerprint_hash')),
    )
    op.create_index('ix_fingerprints_hash', 'lead_fingerprints', ['fingerprint_hash'], unique=False)
    op.create_index('ix_fingerprints_startup', 'lead_fingerprints', ['startup_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fingerprints_startup', table_name='lead_fingerprints')
    op.drop_index('ix_fingerprints_hash', table_name='lead_fingerprints')
    op.drop_table('lead_fingerprints')
    op.drop_index('ix_outcomes_status', table_name='agent_outcomes')
    op.drop_index('ix_outcomes_startup_agent', table_name='agent_outcomes')
    op.drop_index('ix_outcomes_created', table_name='agent_outcomes')
    op.drop_table('agent_outcomes')
    op.drop_index('ix_memstore_type', table_name='agent_memory_store')
    op.drop_index('ix_memstore_startup_agent', table_name='agent_memory_store')
    op.drop_index('ix_memstore_key', table_name='agent_memory_store')
    op.drop_table('agent_memory_store')
    # ### end Alembic commands ###
