import React, { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { useStartupStore } from '../stores/startup-store';
import { Shield, Brain, Zap, Clock, AlertTriangle } from 'lucide-react';
import { cn } from '../lib/utils';
import { PageMeta } from '../components/ui/PageMeta';

interface DebateVerdict {
    id: string;
    created_at: string;
    payload: {
        yc_stance: string;
        musk_stance: string;
        unified_recommendation: string;
    };
}

export default function WarRoomDashboard() {
    const { activeStartupId } = useStartupStore();
    const [verdicts, setVerdicts] = useState<DebateVerdict[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchVerdicts = async () => {
            if (!activeStartupId) return;
            try {
                const data = await (api as any).getWarRoomVerdicts(activeStartupId);
                setVerdicts(data);
            } catch (error) {
                console.error('Failed to fetch war room verdicts:', error);
            } finally {
                setLoading(false);
            }
        };

        fetchVerdicts();

        // Poll every 30 seconds for new escalating debates
        const interval = setInterval(fetchVerdicts, 30000);
        return () => clearInterval(interval);
    }, [activeStartupId]);

    return (
        <div className="max-w-6xl mx-auto pb-20 mt-8">
            <PageMeta title="War Room | MomentAIc" description="Review automated debate outcomes from strategic AI advisors." />

            <div className="mb-12">
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-purple-500/30 bg-purple-500/10 text-purple-400 font-mono text-xs mb-4">
                    <Shield className="w-3 h-3" /> AUTONOMIC_BOARD_OF_DIRECTORS
                </div>
                <h1 className="text-4xl md:text-5xl font-black text-white mb-4 tracking-tighter uppercase relative group">
                    The <span className="text-transparent bg-clip-text bg-gradient-to-r from-red-500 to-purple-500">Autonomic Board</span>
                </h1>
                <p className="text-gray-400 font-mono text-sm max-w-2xl border-l-2 border-purple-500 pl-4">
                    When critical Heartbeat metrics drop, your Ghost Co-Founders (YC Partner & Elon Musk) are automatically summoned into an asymmetric debate loop. Below are the executing directives generated by the Swarm.
                </p>
            </div>

            {loading ? (
                <div className="flex items-center justify-center h-64 border border-white/10 border-dashed rounded-xl bg-white/[0.02]">
                    <div className="flex items-center gap-3 font-mono text-purple-500">
                        <div className="w-2 h-2 bg-purple-500 rounded-full animate-ping" />
                        SYNTHESIZING_STRATEGY_LOOP...
                    </div>
                </div>
            ) : verdicts.length === 0 ? (
                <div className="flex flex-col items-center justify-center p-12 text-center border border-white/5 border-dashed rounded-xl bg-black/40 backdrop-blur-sm">
                    <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-green-500/20 to-emerald-500/5 flex items-center justify-center mb-6">
                        <Shield className="w-8 h-8 text-green-500" />
                    </div>
                    <h3 className="text-xl font-bold font-mono text-white mb-2">SYSTEMS NOMINAL</h3>
                    <p className="text-gray-500 text-sm max-w-md">No metrics have triggered an algorithmic escalation. Your synthetic board remains on standby, continuously analyzing the Heartbeat Engine.</p>
                </div>
            ) : (
                <div className="space-y-8">
                    {verdicts.map((verdict, idx) => (
                        <div key={verdict.id} className="relative bg-[#0a0a0f]/60 backdrop-blur-xl border border-red-500/20 p-8 clip-corner-4 hover:border-red-500/50 transition-colors shadow-[0_0_30px_rgba(239,68,68,0.05)]">
                            <div className="absolute top-0 right-0 p-4 opacity-50">
                                <AlertTriangle className="w-24 h-24 text-red-500/10" />
                            </div>

                            <div className="flex items-center justify-between mb-8 pb-4 border-b border-white/10 relative z-10">
                                <div className="flex items-center gap-3 text-red-400 font-mono text-xs uppercase">
                                    <div className="w-2 h-2 bg-red-500 rounded-full animate-pulse" />
                                    ESCALATION_DETECTED
                                </div>
                                <div className="flex items-center gap-2 text-gray-500 font-mono text-xs">
                                    <Clock className="w-3 h-3" />
                                    {new Date(verdict.created_at).toLocaleString()}
                                </div>
                            </div>

                            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8 relative z-10">
                                {/* YC Advisor Output */}
                                <div className="bg-black/80 border border-orange-500/30 p-5 rounded-lg shadow-[inset_0_0_20px_rgba(249,115,22,0.05)]">
                                    <div className="flex items-center gap-2 text-orange-400 font-bold font-mono text-sm mb-4 border-b border-orange-500/20 pb-2">
                                        <Brain className="w-4 h-4 animate-pulse" /> YC_ADVISOR // TRUTH_PROTOCOL
                                    </div>
                                    <p className="text-orange-100/80 font-mono text-sm leading-relaxed whitespace-pre-wrap">{verdict.payload.yc_stance}</p>
                                </div>

                                {/* Musk Enforcer Output */}
                                <div className="bg-black/80 border border-blue-500/30 p-5 rounded-lg shadow-[inset_0_0_20px_rgba(59,130,246,0.05)]">
                                    <div className="flex items-center gap-2 text-blue-400 font-bold font-mono text-sm mb-4 border-b border-blue-500/20 pb-2">
                                        <Zap className="w-4 h-4 animate-pulse" /> MUSK_ENFORCER // BURN_THE_BOATS
                                    </div>
                                    <p className="text-blue-100/80 font-mono text-sm leading-relaxed whitespace-pre-wrap">{verdict.payload.musk_stance}</p>
                                </div>
                            </div>

                            {/* Unified Recommendation */}
                            <div className="relative z-10 bg-gradient-to-r from-purple-900/60 to-black border border-purple-500/60 p-6 rounded-lg clip-corner-2 hover:shadow-[0_0_30px_rgba(168,85,247,0.3)] transition-all">
                                <div className="text-[10px] font-mono text-purple-400 tracking-widest uppercase mb-3 flex items-center gap-2">
                                    <span className="w-2 h-2 rounded-full bg-purple-500 animate-pulse" />
                                    /// AUTONOMIC_SYNTHESIS (EXECUTABLE_DIRECTIVE)
                                </div>
                                <div className="text-lg md:text-xl font-medium text-white leading-relaxed border-l-2 border-purple-500/50 pl-4">
                                    {verdict.payload.unified_recommendation}
                                </div>

                                <div className="mt-6 flex flex-wrap gap-3">
                                    <button className="px-6 py-2 bg-purple-600 hover:bg-purple-500 text-white font-bold font-mono text-sm rounded border border-purple-400 shadow-[0_0_15px_rgba(147,51,234,0.5)] transition-all hover:scale-[1.02]">
                                        AUTHORIZE // EXECUTE MULTIPLIER
                                    </button>
                                    <button className="px-6 py-2 bg-black border border-white/20 hover:border-red-500 hover:text-red-400 text-white font-mono text-sm rounded transition-all">
                                        OVERRIDE // MANUAL CONTROL
                                    </button>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
}
