"""
Deliverable Service
Generates tangible files (PDF, CSV, MD) from AI output.
This converts "talk" into "action" deliverables.
"""

import os
import csv
import io
from typing import Dict, List, Any, Optional
from datetime import datetime
import structlog
from fpdf import FPDF

# Try to import docx, but fail gracefully if not installed
try:
    from docx import Document
    from docx.shared import Pt
    HAS_DOCX = True
except ImportError:
    HAS_DOCX = False

logger = structlog.get_logger()

# Directory to store generated vault files
# Use relative path for Docker compatibility
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
VAULT_DIR = os.path.join(BASE_DIR, "static", "vault")
os.makedirs(VAULT_DIR, exist_ok=True)

class DeliverableService:
    """
    Service to generate professional deliverables.
    types: PDF (Plans), CSV (Data/Finance), DOCX (Legal/Contracts)
    """
    
    def _get_filepath(self, filename: str) -> str:
        return os.path.join(VAULT_DIR, filename)
    
    def _get_public_url(self, filename: str) -> str:
        # Assuming static files are served from /static/vault
        return f"/static/vault/{filename}"

    async def generate_business_plan_pdf(self, content: Dict[str, Any], company_name: str) -> Dict[str, str]:
        """Generate a professional PDF Business Plan"""
        filename = f"{company_name.replace(' ', '_')}_Business_Plan.pdf"
        filepath = self._get_filepath(filename)
        
        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_font("Arial", "B", 24)
        pdf.cell(0, 20, f"Strategic Plan: {company_name}", ln=True, align="C")
        pdf.ln(10)
        
        pdf.set_font("Arial", "I", 12)
        pdf.cell(0, 10, f"Generated by MomentAIc OS on {datetime.now().strftime('%Y-%m-%d')}", ln=True, align="C")
        pdf.ln(20)
        
        # content logic
        sections = [
            ("Executive Summary", content.get("executive_summary", "")),
            ("Market Analysis", content.get("market_analysis", "")),
            ("Growth Strategy", content.get("growth_strategy", "")),
            ("Financial Projections", content.get("financial_projections", "")),
        ]
        
        for title, text in sections:
            if not text:
                continue
            
            pdf.set_font("Arial", "B", 16)
            pdf.set_text_color(40, 40, 40)
            pdf.cell(0, 10, title, ln=True)
            pdf.ln(5)
            
            pdf.set_font("Arial", "", 11)
            pdf.set_text_color(0, 0, 0)
            
            # Simple word wrap simulation
            pdf.multi_cell(0, 6, text)
            pdf.ln(10)
            
        pdf.output(filepath)
        
        return {
            "title": "Strategic Business Plan",
            "type": "PDF",
            "url": self._get_public_url(filename),
            "created_at": datetime.now().isoformat()
        }

    async def generate_financial_model_csv(self, metrics: Dict[str, Any], company_name: str) -> Dict[str, str]:
        """Generate a CSV Financial Model (Burn Rate, P&L)"""
        filename = f"{company_name.replace(' ', '_')}_Financial_Model.csv"
        filepath = self._get_filepath(filename)
        
        rows = []
        
        # Header
        rows.append(["MomentAIc Generated Financial Model", f"Company: {company_name}", datetime.now().strftime('%Y-%m-%d')])
        rows.append([])
        
        # Monthly Projections Header
        months = ["Metric"] + [f"Month {i+1}" for i in range(12)] + ["Total Year 1"]
        rows.append(months)
        
        # Revenue
        revenue_base = metrics.get("monthly_revenue", 0)
        growth_rate = metrics.get("growth_rate_percent", 5) / 100
        
        rev_row = ["Revenue ($)"]
        current_rev = revenue_base
        total_rev = 0
        for _ in range(12):
            rev_row.append(round(current_rev, 2))
            total_rev += current_rev
            current_rev *= (1 + growth_rate)
        rev_row.append(round(total_rev, 2))
        rows.append(rev_row)
        
        # Expenses (Simplified)
        burn_rate = metrics.get("monthly_burn", 5000)
        exp_row = ["Expenses ($)"]
        current_exp = burn_rate
        total_exp = 0
        for _ in range(12):
            exp_row.append(round(current_exp, 2))
            total_exp += current_exp
            current_exp *= 1.02 # Assuming 2% monthly inflation/hiring
        exp_row.append(round(total_exp, 2))
        rows.append(exp_row)
        
        # Profit/Loss
        rows.append([])
        rows.append(["NET Income"])
        
        # Valuation (Live Data Injection)
        if "valuation_multiple" in metrics:
            rows.append([])
            rows.append([f"LIVE VALUATION (Based on {metrics.get('valuation_multiple')}x ARR)"])
            
            # Simple valuation calculation based on Year 1 ARR
            # ARR = last month revenue * 12
            arr = (current_rev / (1+growth_rate)) * 12 
            val = arr * metrics.get("valuation_multiple", 5)
            rows.append([f"Estimated Post-Money: ${round(val, 2)}"])
            rows.append([f"Note: {metrics.get('valuation_note', '')}"])
        
        with open(filepath, 'w', newline='') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerows(rows)
            
        return {
            "title": "Financial Model (Year 1)",
            "type": "CSV",
            "url": self._get_public_url(filename),
            "created_at": datetime.now().isoformat()
        }

    async def generate_cohort_analysis_csv(self, industry: str, benchmarks: Dict[str, float], company_name: str) -> Dict[str, str]:
        """Generate a Cohort Analysis CSV with Benchmark comparison"""
        filename = f"{company_name.replace(' ', '_')}_Cohort_Analysis.csv"
        filepath = self._get_filepath(filename)
        
        rows = []
        rows.append(["Cohort Analysis & Retention", f"Industry: {industry}", datetime.now().strftime('%Y-%m-%d')])
        rows.append([])
        
        # Header
        rows.append(["Cohort Month", "Users", "Month 1", "Month 2", "Month 3", "Month 6", "Month 12"])
        
        # Simulate some cohorts
        for i in range(1, 7):
            month = f"2025-{i:02d}"
            users = 100 + (i * 20)
            
            # Retention decay based on benchmark but simulated
            m1 = benchmarks.get("month_1", 0.5)
            m3 = benchmarks.get("month_3", 0.3)
            
            row = [month, users, f"{int(m1*100)}%", f"{int(m1*0.9*100)}%", f"{int(m3*100)}%", "-", "-"]
            rows.append(row)
            
        rows.append([])
        rows.append(["INDUSTRY BENCHMARKS (Live Data)"])
        rows.append(["Month 1", f"{int(benchmarks.get('month_1',0)*100)}%"])
        rows.append(["Month 3", f"{int(benchmarks.get('month_3',0)*100)}%"])
        rows.append(["Month 6", f"{int(benchmarks.get('month_6',0)*100)}%"])
        rows.append(["Note", benchmarks.get("insight", "")])
            
        with open(filepath, 'w', newline='') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerows(rows)
            
        return {
            "title": "Cohort Analysis (Live Benchmarks)",
            "type": "CSV",
            "url": self._get_public_url(filename),
            "created_at": datetime.now().isoformat()
        }

    async def generate_legal_contract(self, contract_type: str, parties: Dict[str, str], company_name: str) -> Dict[str, str]:
        """Generate a Legal Contract (DOCX or MD fallback)"""
        filename = f"{company_name.replace(' ', '_')}_{contract_type}.docx"
        filepath = self._get_filepath(filename)
        
        # Content generation (simplified template)
        title = f"{contract_type.upper().replace('_', ' ')} AGREEMENT"
        
        if HAS_DOCX:
            doc = Document()
            doc.add_heading(title, 0)
            
            p = doc.add_paragraph(f"This agreement is made on {datetime.now().strftime('%B %d, %Y')} between:")
            doc.add_paragraph(f"Party A: {parties.get('party_a', company_name)}")
            doc.add_paragraph(f"Party B: {parties.get('party_b', '[Counterparty Name]')}")
            
            doc.add_heading('1. Purpose', level=1)
            doc.add_paragraph("The purpose of this agreement is to define the relationship and obligations...")
            
            doc.add_heading('2. Term', level=1)
            doc.add_paragraph("This agreement shall commence on the date hereof and continue until terminated.")
            
            doc.add_heading('3. Confidentiality', level=1)
            doc.add_paragraph("Both parties agree to keep all proprietary information confidential.")
            
            doc.add_paragraph("\n\n___________________________\nSigned (Party A)")
            
            doc.save(filepath)
        else:
            # Fallback to text file if docx missing
            filename = filename.replace('.docx', '.txt')
            filepath = self._get_filepath(filename)
            with open(filepath, 'w') as f:
                f.write(f"{title}\n\n")
                f.write(f"Date: {datetime.now().strftime('%B %d, %Y')}\n\n")
                f.write(f"Between {parties.get('party_a', company_name)} and {parties.get('party_b', '[Counterparty Name]')}\n\n")
                f.write("1. PURPOSE\nThe purpose is...\n\n")
        
        return {
            "title": f"{contract_type.replace('_', ' ').title()}",
            "type": "DOCX" if HAS_DOCX else "TXT",
            "url": self._get_public_url(filename),
            "created_at": datetime.now().isoformat()
        }

    async def generate_day_one_pack(self, company_name: str, industry: str) -> List[Dict[str, str]]:
        """
        Generates the 'Day 1' bundle:
        - Strategy Plan
        - Financial Model
        - Content Calendar
        - NDA
        """
        deliverables = []
        
        # 1. Strategy Plan (Simulated AI content for now)
        plan_content = {
            "executive_summary": f"{company_name} aims to disrupt the {industry} market with AI-driven solutions.",
            "market_analysis": f"The {industry} market is growing rapidly...",
            "growth_strategy": "1. Viral loop via referrals\n2. Content marketing\n3. Strategic partnerships",
            "financial_projections": "Projected to reach profitability in Month 9."
        }
        deliverables.append(await self.generate_business_plan_pdf(plan_content, company_name))
        
        # 2. Financial Model
        fin_metrics = {"monthly_revenue": 0, "monthly_burn": 2000, "growth_rate_percent": 15}
        # Assuming CFO/finance agent usually calls this with live data, but for direct bulk generation we inject it here too
        from app.services.live_data_service import live_data_service
        try:
            multiples = await live_data_service.get_saas_multiples()
            fin_metrics["valuation_multiple"] = multiples["median_arr_multiple"]
            fin_metrics["valuation_note"] = "Live SaaS Index"
        except:
            pass
            
        deliverables.append(await self.generate_financial_model_csv(fin_metrics, company_name))
        
        # 3. Cohort Analysis (New Live Data)
        try:
            benchmarks = await live_data_service.get_retention_benchmarks(industry)
            deliverables.append(await self.generate_cohort_analysis_csv(industry, benchmarks, company_name))
        except Exception as e:
            logger.error("Cohort generation failed", error=str(e))
        
        # 4. Legal
        deliverables.append(await self.generate_legal_contract("Non_Disclosure_Agreement", {}, company_name))
        
        return deliverables

# Singleton
deliverable_service = DeliverableService()
