"""
Visual Asset Generation Pipeline
Utilizes Google's Imagen 3.0/4.0 models via the new google-genai SDK 
to create high-fidelity visual assets, converting them to Base64 data URIs
for immediate frontend rendering.
"""

from typing import Optional, List, Dict, Any
import base64
import structlog
from google import genai
from google.genai.types import GenerateImagesConfig
from app.core.config import settings

logger = structlog.get_logger()

class AssetGenerationService:
    def __init__(self):
        # The SDK automatically uses GOOGLE_API_KEY from the environment
        if not settings.google_api_key:
            logger.warning("google_api_key_missing", component="Image Generation")
            self.client = None
        else:
            self.client = genai.Client(api_key=settings.google_api_key)
            
    async def generate_image(self, prompt: str, aspect_ratio: str = "1:1") -> str:
        """
        Generates an image from a text prompt and returns it as a Base64 encoded string (Data URI)
        so the frontend can render it immediately without an S3 bucket.
        """
        if not self.client:
            raise ValueError("Google API key not configured for image generation.")
            
        logger.info("generating_image_asset", prompt=prompt, aspect_ratio=aspect_ratio)
        
        # Valid aspect ratios: "1:1", "3:4", "4:3", "16:9", "9:16"
        valid_ratios = ["1:1", "3:4", "4:3", "16:9", "9:16"]
        if aspect_ratio not in valid_ratios:
            aspect_ratio = "1:1"
            
        try:
            # Using Imagen 3 as the default production workhorse
            result = await self.client.aio.models.generate_images(
                model='imagen-3.0-generate-001',
                prompt=prompt,
                config=GenerateImagesConfig(
                    number_of_images=1,
                    output_mime_type="image/png",
                    aspect_ratio=aspect_ratio,
                    person_generation="ALLOW_ADULT" # Crucial for generating ad models
                )
            )
            
            if not result.generated_images:
                raise ValueError("No images generated by the model.")
                
            # The API returns raw image bytes.
            # We encode this into a base64 Data URI so the frontend <img> tag can consume it natively.
            image_bytes = result.generated_images[0].image.image_bytes
            base64_encoded = base64.b64encode(image_bytes).decode('utf-8')
            data_uri = f"data:image/png;base64,{base64_encoded}"
            
            logger.info("image_asset_generated_successfully", size_bytes=len(image_bytes))
            return data_uri
            
        except Exception as e:
            logger.error("image_generation_failed", error=str(e), prompt=prompt)
            raise

asset_generation_service = AssetGenerationService()
