"""
Video Service
Handles Script Generation ("Dreamer Mode") and Sovereign Mode directing.
"""

import structlog
from typing import Dict, Any, List
from app.core.config import settings
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

logger = structlog.get_logger()

class VideoService:
    def __init__(self):
        self.llm = ChatGoogleGenerativeAI(
            model="gemini-2.0-flash-exp",
            google_api_key=settings.google_api_key,
            temperature=0.7
        ) if settings.google_api_key else None

    async def generate_script(self, news_item: Dict[str, Any], style: str = "Cyberpunk News Anchor") -> Dict[str, Any]:
        """
        Generate a viral short-video script from a news item.
        """
        logger.info("generating_video_script", topic=news_item.get("title"))
        
        prompt = ChatPromptTemplate.from_messages([
            ("system", """You are Nolan Pro, a legendary Short-Form Video Director.
            Style: {style}
            Goal: Create a viral 30-second video script (TikTok/Shorts format).
            
            Structure:
            1. HOOK (0-3s): Visual disruption + controversial statement.
            2. BODY (3-25s): The news, explained simply but with high energy.
            3. CTA (25-30s): "News generated by Symbiotask. Create yours in 1 click."
            
            Output Format:
            - [Visual Cue] Audio/Vibe
            - (Narrator): Line of dialogue.
            """),
            ("user", """Create a script for this news:
            Title: {title}
            Context: {snippet}
            Source: {source}
            """)
        ])
        
        chain = prompt | self.llm | StrOutputParser()
        
        script = await chain.ainvoke({
            "style": style,
            "title": news_item.get("title"),
            "snippet": news_item.get("snippet"),
            "source": news_item.get("source")
        })
        
        return {
            "title": f"Viral Short: {news_item.get('title')}",
            "script": script,
            "style": style,
            "estimated_duration": "30s"
        }

    async def render_video(self, script_data: Dict[str, Any], user_email: str = None) -> Dict[str, Any]:
        """
        Dispatches render job to Symbiotask.com
        """
        from app.services.ecosystem_service import ecosystem_service
        
        logger.info("dispatching_symbiotask_render", title=script_data['title'], user=user_email)
        
        # Dispatch to Symbiotask
        response = await ecosystem_service.generate_symbiotask_video(script_data, user_email=user_email)
        
        if response.get("success"):
            return {
                "status": "queued",
                "job_id": response["data"].get("job_id", "symbio_123"),
                "platform": "Symbiotask.com",
                "message": "Video generation started on Symbiotask grid.",
                "details": response.get("data")
            }
        else:
             logger.error("symbiotask_failed", error=response.get("error"))
             return {
                 "status": "failed",
                 "error": response.get("error"),
                 "message": "Symbiotask dispatch failed. Check API connectivity."
             }

video_service = VideoService()
